version: "3.6"
services:
  peer-server:
    image: buttcloud/butt-peer-server:v1.0.1
    ports:
      - "8008:8008"
    environment:
      - ssb_host=peer-server
    volumes:
      - ssb:/home/node/.ssb
    networks:
      - default
    labels:
      - "traefik.enable=false"
    deploy:
      restart_policy:
        condition: on-failure

  landing:
    image: buttcloud/butt-landing:v1.0.3
    environment:
      - ssb_host=peer-server
      - ssb_landing__host=landing
    volumes:
      - ssb:/home/node/.ssb
    networks:
      - proxy
      - default
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.backend=landing"
        - "traefik.port=8901"
        - "traefik.frontend.rule=Host:${HOST:-example.butt.nz}"
        - "traefik.docker.network=proxy"
      restart_policy:
        condition: on-failure

  proxy:
    image: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: traefik.toml
        target: /etc/traefik/traefik.toml
    networks:
      - proxy
    labels:
      - "traefik.enable=false"
    deploy:
      placement:
        constraints: [node.role == manager]   
      restart_policy:
        condition: on-failure

configs:  
  traefik.toml:
    file: ./traefik.toml

networks:  
  proxy:
    external: true

volumes:
  ssb:
